# Generated by Django 5.2.14 on 2026-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('gardener', 'Gardener'), ('electrician', 'Electrician'), ('plumber', 'Plumber')], default='customer', max_length=20),
        ),
    ]
