# Generated by Django 5.2.14 on 2026-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_favoriteprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='location_source',
            field=models.CharField(choices=[('live', 'Current Location'), ('manual', 'Manual Location')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Custom address label such as Home, Office, Parents' Home, etc.", max_length=100),
        ),
    ]
