# Generated by Django 5.2.14 on 2026-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
