# Generated by Django 5.2.14 on 2026-06-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivate_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
