"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
from pathlib import Path
from urllib.parse import urlparse


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT HELPERS
# ============================================================

def _strip_url_scheme(value: str) -> str:
    return (
        value
        .replace("https://", "")
        .replace("http://", "")
        .strip("/")
    )


def _database_from_url(database_url: str) -> dict:
    parsed = urlparse(database_url)

    query = dict(
        part.split("=", 1)
        for part in parsed.query.split("&")
        if "=" in part
    )

    options = {}

    sslmode = query.get("sslmode")

    if sslmode:
        options["sslmode"] = sslmode

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "",
        "PORT": parsed.port or 5432,
        "OPTIONS": options,
    }


def _load_env_file(path: Path) -> None:
    """
    Load environment variables from .env.

    Existing operating-system environment variables
    are not overwritten.
    """

    if not path.is_file():
        return

    for line in path.read_text().splitlines():

        line = line.strip()

        if (
            not line
            or line.startswith("#")
            or "=" not in line
        ):
            continue

        key, _, value = line.partition("=")

        os.environ.setdefault(
            key.strip(),
            value.strip(),
        )


def _env_bool(key: str) -> bool:
    return (
        os.environ[key]
        .strip()
        .lower()
        in ("1", "true", "yes", "on")
    )


def _env_list(key: str) -> list[str]:
    return [
        item.strip()
        for item in os.environ[key].split(",")
        if item.strip()
    ]


# Prefer backend/.env.
# Fall back to project-root .env for older layouts.

_load_env_file(BASE_DIR / ".env")
_load_env_file(BASE_DIR.parent / ".env")


# ============================================================
# CORE DJANGO SETTINGS
# ============================================================

SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = _env_bool("DEBUG")

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS"
)

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS"
)

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS"
)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # ASGI
    "daphne",

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Channels
    "channels",

    # REST Framework
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",

    # Third-party
    "corsheaders",
    "anymail",
    "storages",

    # Project apps
    "accounts",
    "services",
    "adminpanel",
    "uploads",
    "providers",
    "service_requests",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI / ASGI
# ============================================================

ROOT_URLCONF = "backend.urls"


TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends."
            "django.DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


WSGI_APPLICATION = "backend.wsgi.application"

ASGI_APPLICATION = "backend.asgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = os.environ.get(
    "DATABASE_URL"
)


_DB_COMMON = {
    "CONN_MAX_AGE": 600,
    "CONN_HEALTH_CHECKS": True,
}


if DATABASE_URL:

    DATABASES = {
        "default": {
            **_database_from_url(
                DATABASE_URL
            ),
            **_DB_COMMON,
        }
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": (
                "django.db.backends.postgresql"
            ),
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ["DB_HOST"],
            "PORT": os.environ["DB_PORT"],
            **_DB_COMMON,
        }
    }


# ============================================================
# REDIS
# ============================================================

REDIS_HOST = os.environ["REDIS_HOST"]

REDIS_PORT = int(
    os.environ["REDIS_PORT"]
)

REDIS_MAX_CONNECTIONS = int(
    os.environ.get(
        "REDIS_MAX_CONNECTIONS",
        "4",
    )
)

REDIS_URL = (
    os.environ.get("REDIS_URL")
    or
    f"redis://{REDIS_HOST}:{REDIS_PORT}"
)


# ============================================================
# CACHE
# ============================================================

# Local memory cache by default.
#
# To use Redis:
#
# CACHE_BACKEND=redis

CACHE_BACKEND = (
    os.environ
    .get(
        "CACHE_BACKEND",
        "locmem",
    )
    .strip()
    .lower()
)


if CACHE_BACKEND == "redis":

    redis_cache_location = (
        REDIS_URL
        if REDIS_URL.endswith("/1")
        else f"{REDIS_URL.rstrip('/')}/1"
    )

    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends."
                "redis.RedisCache"
            ),
            "LOCATION": (
                redis_cache_location
            ),
            "OPTIONS": {
                "max_connections": (
                    REDIS_MAX_CONNECTIONS
                ),
                "socket_connect_timeout": 2,
                "socket_timeout": 2,
                "retry_on_timeout": False,
            },
        }
    }

else:

    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends."
                "locmem.LocMemCache"
            ),
            "LOCATION": (
                "marketplace-default"
            ),
        }
    }


# ============================================================
# DJANGO CHANNELS / WEBSOCKET
# ============================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": (
            "channels_redis.core."
            "RedisChannelLayer"
        ),
        "CONFIG": {
            "hosts": [
                {
                    "address": REDIS_URL,
                    "max_connections": (
                        REDIS_MAX_CONNECTIONS
                    ),
                }
            ],
            "capacity": 100,
        },
    },
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"


DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication."
        "CachedTokenAuthentication",
    ),
}


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "accounts.User"


# ============================================================
# MEDIA / S3 STORAGE
# ============================================================

USE_S3 = bool(
    os.environ.get(
        "AWS_STORAGE_BUCKET_NAME"
    )
)


if USE_S3:

    AWS_ACCESS_KEY_ID = os.environ[
        "AWS_ACCESS_KEY_ID"
    ]

    AWS_SECRET_ACCESS_KEY = os.environ[
        "AWS_SECRET_ACCESS_KEY"
    ]

    AWS_STORAGE_BUCKET_NAME = os.environ[
        "AWS_STORAGE_BUCKET_NAME"
    ]

    AWS_S3_REGION_NAME = os.environ.get(
        "AWS_S3_REGION_NAME",
        "us-east-1",
    )

    AWS_S3_ENDPOINT_URL = os.environ.get(
        "AWS_S3_ENDPOINT_URL",
        "",
    )

    AWS_S3_PUBLIC_BASE_URL = os.environ.get(
        "AWS_S3_PUBLIC_BASE_URL",
        "",
    )

    AWS_S3_CUSTOM_DOMAIN = _strip_url_scheme(
        os.environ.get(
            "AWS_S3_CUSTOM_DOMAIN",
            "",
        )
    )

    if (
        AWS_S3_PUBLIC_BASE_URL
        and not AWS_S3_CUSTOM_DOMAIN
    ):

        AWS_S3_CUSTOM_DOMAIN = (
            _strip_url_scheme(
                AWS_S3_PUBLIC_BASE_URL
            )
        )

    AWS_S3_ADDRESSING_STYLE = "path"

    AWS_S3_SIGNATURE_VERSION = "s3v4"

    AWS_S3_FILE_OVERWRITE = False

    AWS_DEFAULT_ACL = None

    AWS_QUERYSTRING_AUTH = False

    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }


    STORAGES = {
        "default": {
            "BACKEND": (
                "storages.backends.s3."
                "S3Storage"
            ),
        },
        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles."
                "storage.StaticFilesStorage"
            ),
        },
    }


    if AWS_S3_PUBLIC_BASE_URL:

        MEDIA_URL = (
            AWS_S3_PUBLIC_BASE_URL.rstrip("/")
            + "/"
        )

    elif AWS_S3_CUSTOM_DOMAIN:

        MEDIA_URL = (
            f"https://"
            f"{AWS_S3_CUSTOM_DOMAIN}/"
        )

    elif AWS_S3_ENDPOINT_URL:

        MEDIA_URL = (
            AWS_S3_ENDPOINT_URL.rstrip("/")
            + "/"
        )

    else:

        MEDIA_URL = (
            f"https://"
            f"{AWS_STORAGE_BUCKET_NAME}"
            f".s3."
            f"{AWS_S3_REGION_NAME}"
            f".amazonaws.com/"
        )

else:

    MEDIA_URL = "/media/"

    MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# GOOGLE MAPS
# ============================================================

# Server-side only.
# Never expose this key to the frontend.

GOOGLE_MAPS_API_KEY = os.environ.get(
    "GOOGLE_MAPS_API_KEY",
    "",
)


# ============================================================
# EMAIL
# LOCAL DEVELOPMENT — GMAIL SMTP
# ============================================================

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.gmail.com",
)

EMAIL_PORT = int(
    os.environ.get(
        "EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = (
    os.environ
    .get(
        "EMAIL_USE_TLS",
        "True",
    )
    .strip()
    .lower()
    in (
        "1",
        "true",
        "yes",
        "on",
    )
)

EMAIL_USE_SSL = (
    os.environ
    .get(
        "EMAIL_USE_SSL",
        "False",
    )
    .strip()
    .lower()
    in (
        "1",
        "true",
        "yes",
        "on",
    )
)

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL


# ============================================================
# LOGGING
# ============================================================

LOGGING = {
    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "class": (
                "logging.StreamHandler"
            ),
        },
    },

    "root": {
        "handlers": [
            "console",
        ],
        "level": "INFO",
    },

    "loggers": {

        "accounts.email_service": {
            "handlers": [
                "console",
            ],
            "level": "INFO",
            "propagate": False,
        },

    },
}

# ============================================================
# CELERY
# ============================================================

CELERY_BROKER_URL = REDIS_URL

CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = [
    "json",
]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True