# Generated by Django 5.2.14 on 2026-05-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
