# Generated by Django 5.2.14 on 2026-05-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_address_alter_user_phone_customeraddress'),
        ('services', '0008_delete_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='accounts.customeraddress'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='polygon_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
