# Generated by Django 5.2.14 on 2026-08-21 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_dynamic_service_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='services_bo_status_e16d15_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='services_bo_provide_8afccd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='services_bo_created_784d68_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='services_qu_status_bfcddd_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['provider', 'status'], name='services_qu_provide_73cc97_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['-created_at'], name='services_qu_created_35102e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider'], name='services_re_provide_a650c6_idx'),
        ),
    ]
