# Generated by Django 5.2.14 on 2026-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
