# Generated by Django 5.2.14 on 2026-09-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicerequest_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
