# Generated by Django 5.2.14 on 2026-08-19 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
        ('service_requests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True, default='')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='providers.providerprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='service_requests.customerservicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('service_request', 'provider_profile'), name='unique_provider_quotation_per_request')],
            },
        ),
    ]
