# Generated by Django 5.2.14 on 2026-08-19 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
        ('service_requests', '0003_providerquotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to='providers.providerprofile')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='service_requests.providerquotation')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='service_requests.customerservicerequest')),
            ],
        ),
    ]
