# Generated by Django 5.2.14 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_servicenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenotification',
            name='notification_type',
            field=models.CharField(choices=[('new_request', 'New Service Request'), ('quotation_received', 'Quotation Received'), ('quotation_accepted', 'Quotation Accepted'), ('booking_created', 'Booking Created'), ('work_started', 'Work Started'), ('work_completed', 'Work Completed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_status', 'Booking Status Updated'), ('review_received', 'Review Received'), ('general', 'General')], default='general', max_length=40),
        ),
    ]
