# Generated by Django 5.2.14 on 2026-07-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='provider_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='providerservicearea',
            name='provider_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='providers.providerprofile'),
        ),
        migrations.AddConstraint(
            model_name='provideravailability',
            constraint=models.UniqueConstraint(fields=('provider_profile', 'day_of_week', 'start_time', 'end_time'), name='unique_provider_availability_slot'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.UniqueConstraint(fields=('provider_profile', 'category'), name='unique_provider_service_category'),
        ),
    ]
