# Generated by Django 5.2.14 on 2026-09-07 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='current_location_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='location_source',
            field=models.CharField(blank=True, choices=[('live', 'Live Location'), ('manual', 'Manual Location')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
