# Generated by Django 5.2.14 on 2026-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/'),
        ),
    ]
