# Generated by Django 5.2.14 on 2026-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_spotlightimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
