# Generated by Django 5.2.14 on 2026-08-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_servicecategory_is_popular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_providers', models.BooleanField(default=False)),
                ('manage_customers', models.BooleanField(default=False)),
                ('manage_services', models.BooleanField(default=False)),
                ('manage_bookings', models.BooleanField(default=False)),
                ('manage_quotes', models.BooleanField(default=False)),
                ('view_reports', models.BooleanField(default=False)),
                ('manage_spotlights', models.BooleanField(default=False)),
                ('manage_admin_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
