# Generated by Django 5.2.14 on 2026-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_adminpermissionprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['status'], name='adminpanel__status_1ff2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['status', 'is_popular'], name='adminpanel__status_ad870f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['display_order', 'name'], name='adminpanel__display_4154b8_idx'),
        ),
        migrations.AddIndex(
            model_name='spotlightimage',
            index=models.Index(fields=['is_active', 'display_order'], name='adminpanel__is_acti_a911ad_idx'),
        ),
    ]
