# Generated by Django 5.2.14 on 2026-09-07 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_provider_radius_km', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum distance within which providers can receive customer service requests.', max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('default_provider_radius_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Default provider preference when a provider has not selected their own radius.', max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_location_matching_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketplace Location Settings',
                'verbose_name_plural': 'Marketplace Location Settings',
            },
        ),
    ]
