# Generated by Django 5.2.14 on 2026-09-07 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_marketplacelocationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelocationsettings',
            name='live_location_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Number of minutes a provider's live GPS location remains valid for marketplace matching.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
